### ISSUE TITLE
map not showing without clearing grav cache

### ISSUE THREAD

**Issue by daz3dpr0z** [deved-it/grav-plugin-google-maps#11]
am hoping to use the plugin and it appears to want to work . on first load of the page the map works fine. when i leave the page and return to the map the page wont load. or it loads but map is not visible. to view the map again i need to clear the grav cache and when done the map shows again. any ideas what is happening here. im getting the same result in firefox and konquror. the map is located http://45.55.176.255/locate. any insight would be really appreciated

**Comment by joostduecker** [comment]
i've got the same problem... any solutions so far?

**Comment by nicholascarroll** [comment]
same.

**Comment by salgua** [comment]
Hi guys, just fixed the problem in v1.0.8. Thank you very much!

**Comment by Lockyc** [comment]
This issue has not been resolved.
Grav cache has to be cleared to display the google maps

**Comment by ghost** [comment]
I'm using this plugin on one of my Grav websites and this bug hasn't been resolved obviously.
