### ISSUE TITLE
E_DEPRECATED – Non-static method Grav\Common\Plugin::isAdmin() should not be called statically

### ISSUE THREAD

**Issue by WhiteWolfSix** [deved-it/grav-plugin-google-maps#12]
After the installation it gives me this error E_DEPRECATED – Non-static method Grav\Common\Plugin::isAdmin() should not be called statically. It is installed locally using WAMP 3.0.6. All other plugins are installed and working correctly.

**Comment by nicholascarroll** [comment]
I also got this and had to uninstall the plugin from CLI:
`bin/gpm uninstall google-maps`

**Comment by WhiteWolfSix** [comment]
Well, plugin itself works in live environment on web. I wonder what is different on localhost.

**Comment by douglasgough** [comment]
When I comment out the call to isAdmin() inside getSubscribedEvents everything works. It doesn't seem to adversely effect anything. What is the purpose of checking to see if we are in the admin plugin?

**Comment by amaury-hanser** [comment]
> When I comment out the call to isAdmin() inside getSubscribedEvents everything works. It doesn't seem to adversely effect anything. What is the purpose of checking to see if we are in the admin plugin?

Same here, thank you for the solution !
