### ISSUE TITLE
Installation succeed, but grav won't work anymore

### ISSUE THREAD

**Issue by amaury-hanser** [deved-it/grav-plugin-google-maps#16]
Hello, 

I tried to install the plugin via `bin/gpm install google-maps`, the installation succeed, but if I try to access to my website (localhost with Wamp or online, I tried both) I got this error:

> Whoops\Exception\ErrorException thrown with message "Non-static method Grav\Common\Plugin::isAdmin() should not be called statically"

> Stacktrace:
> #11 Whoops\Exception\ErrorException in C:\wamp\www\grav\user\plugins\google-maps\google-maps.php:25
> #10 Grav\Common\Plugin:isAdmin in C:\wamp\www\grav\user\plugins\google-maps\google-maps.php:25
> #9 Grav\Plugin\GoogleMapsPlugin:getSubscribedEvents in C:\wamp\www\grav\vendor\symfony\event-dispatcher\EventDispatcher.php:139
> #8 Symfony\Component\EventDispatcher\EventDispatcher:addSubscriber in C:\wamp\www\grav\system\src\Grav\Common\Plugins.php:104
> #7 Grav\Common\Plugins:init in C:\wamp\www\grav\system\src\Grav\Common\Processors\PluginsProcessor.php:18
> #6 Grav\Common\Processors\PluginsProcessor:process in C:\wamp\www\grav\system\src\Grav\Common\Grav.php:126
> #5 Grav\Common\Grav:Grav\Common\{closure} in C:\wamp\www\grav\system\src\Grav\Common\Grav.php:368
> #4 Grav\Common\Grav:Grav\Common\{closure} in C:\wamp\www\grav\system\src\Grav\Common\Grav.php:344
> #3 call_user_func_array in C:\wamp\www\grav\system\src\Grav\Common\Grav.php:344
> #2 Grav\Common\Grav:__call in C:\wamp\www\grav\system\src\Grav\Common\Grav.php:127
> #1 Grav\Common\Grav:measureTime in C:\wamp\www\grav\system\src\Grav\Common\Grav.php:127
> #0 Grav\Common\Grav:process in C:\wamp\www\grav\index.php:52

If I uninstall the plugin, everything works as a charm.
Do you have any idea ?

Thank you in advance.

**Comment by WhiteWolfSix** [comment]
Look at this: https://github.com/deved-it/grav-plugin-google-maps/issues/12
It seems to be a common issue.

**Comment by amaury-hanser** [comment]
Thank you, it works now !
