### ISSUE TITLE
Updating from 1.0.3 to 1.0.8 breaks Grav

### ISSUE THREAD

**Issue by mn113** [deved-it/grav-plugin-google-maps#17]
A fatal error occurred when I tried to update this plugin within Admin.

`Non-static method Grav\Common\Plugin::isAdmin() should not be called statically`
in
`…/user/plugins/google-maps/google-maps.php 25`

It breaks Admin and also my whole grav website. Luckily I took a backup just before this.

I have PHP Version 5.6.25 if it's any help. My Grav is at version 1.1.17, and Admin 1.2.2.

**Comment by ghost** [comment]
I solved like this:

```
 public static function getSubscribedEvents()
    {
       // Don't proceed if we are in the admin plugin
       // if (self::isAdmin()) {
       //     return [];
       // }
		
        return [
            'onShortcodeHandlers' => ['onShortcodeHandlers', 0],
            'onTwigTemplatePaths' => ['onTwigTemplatePaths', 0],
        ];
    }
```

*** But, I don't know this is right. **

**Comment by michaelkonecny** [comment]
The function isAdmin is not static, but is called from a static function of the same class, therefor raises E_DEPRECATED type error on php 5.6 and 7.

I will create a pull request that solves this in a while.
