### ISSUE TITLE
Include in template

### ISSUE THREAD

**Issue by andreaschiona** [deved-it/grav-plugin-google-maps#23]
Hi,

it's possible include the google map in a twig template? 

Thanks,
Andrea

**Comment by MakaryGo** [comment]
Sure it is, just use the normal embedding/including methods from Google Maps documentation :) They are designed (and described) for plain HTML, and that's what we're working with in Twig (almost)
Cheers!

**Comment by andreaschiona** [comment]
Thanks! I read the Google documentation now :)

**Comment by tboulogne** [comment]
hello,

@andreaschiona a simple way to include this into twig : 

Put this into the md file : 
`
[section name="mapplace"]
[google-maps width='100%' lat=48.879099 lng=2.299333 zoom=16 scrollwheel=true panControl=true iconurl='/absolute/path/to/marker/icon.png']
***Nous sommes ici ***
[/google-maps]
[/section]
`

and this into your twig file:

`  {{ shortcode.section.mapplace }}`
